### ISSUE TITLE
Спасибо тебе мил человек!)

### ISSUE THREAD

**Issue by lbarmen** [ciricc/kinopoisk-dualsubs#1]
Спасибо за расширение! 

Из пожеланий: возможность отделить рус. и англ. субтитры, сейчас они в одном тёмной квадрате и сливаются друг с другом. Обычно решают это:
- выделением цвета
- перемещением вверх

**Comment by ciricc** [comment]
Привет. Спасибо за отзыв)

Добавил возможность выделить цветом дорожку в версии 1.3
