### ISSUE TITLE
Дичайший рассинхрон

### ISSUE THREAD

**Issue by ciricc** [ciricc/kinopoisk-dualsubs#11]
Фильм "Время" - примерно начиная с 1:00:00, дикий рассинхрон дорожек.

**Comment by witaway** [comment]
Аналогичная ситуация, сериал "Засланец из космоса". Тайминги не записал, но факт.
Может быть, это стоит решить возможностью установки сдвига субтитров по времени относительно аудиодорожки?
Видел подобное решение в плееере Popcorn Time. Иногда бывает очень удобно.

**Comment by ciricc** [comment]
@witaway в данном случае это баг именно из-за последней обновы. Но возможность установить смещение - хорошая идея. Сейчас реплики выбираются по принципу касания. Если хоть немного плоащади на таймлайне есть общей - то это считаются подходящие реплики. Если их несколько - они потом соединяются в одну.
