### ISSUE TITLE
Субтитры кинопоиска не пропадают. Двойные субтитры накладываются поверх. 

### ISSUE THREAD

**Issue by EazzzyMax** [ciricc/kinopoisk-dualsubs#19]
После добавления кинопоиском возможности выбирать размер субтитров появилась такая проблема.
![image](https://user-images.githubusercontent.com/43323617/197577379-980669a1-3d1a-4813-b7d8-ba34ebd74048.png)

**Comment by ciricc** [comment]
Посмотрю. Видимо фича пока не раскатана на всех

**Comment by EazzzyMax** [comment]
> 
уже норм работает) странно

**Comment by ciricc** [comment]
Исправлено в версии [1.5.0](https://github.com/ciricc/kinopoisk-dualsubs/releases/tag/1.5.0)
