### ISSUE TITLE
Не правильное отображение субтитров

### ISSUE THREAD

**Issue by barczius** [ciricc/kinopoisk-dualsubs#23]
В Докторе Кто на сериях с нумерацией 0, вторые субтитры не верно синхронизируются по таймингу и отображаются не правильно.

**Comment by ciricc** [comment]
Спасибо за отзыв.  Да, действительно есть проблема с 0 эпизодами.

**Comment by ciricc** [comment]
Исправлено в версии [1.7.0](https://github.com/ciricc/kinopoisk-dualsubs/releases/tag/1.7.0)
