### ISSUE TITLE
Возрождение. Исправление бага 

### ISSUE THREAD

**Issue by akseonowww** [ciricc/kinopoisk-dualsubs#32]
Наткнулся вчера на это чудо и разочаровался, что сейчас не работает. Посмотрев код удивился как же просто решается проблема: нужно удалить `yaplayertag` в поиске элемента `[class*="PlayerManager_player"] yaplayertag` ([App.svelte 168 строка](https://github.com/ciricc/kinopoisk-dualsubs/blob/main/src/content-scripts/App.svelte)).

**Comment by ciricc** [comment]
Привет. Спасибо за помощь в исправлении. Залил фикс, https://github.com/ciricc/kinopoisk-dualsubs/commit/773a74e158983e39408bfefff76965cc9a5f7db5. Скоро появится на маркете новая версия

**Comment by akseonowww** [comment]
Здорово, так быстро.
