### ISSUE TITLE
Сторонние субтитры

### ISSUE THREAD

**Issue by akseonowww** [ciricc/kinopoisk-dualsubs#33]
Странно, но некоторые фильмы имея английскую аудио дорожку не имеют английских субтитров — было бы здорово добавить внешние субтитры, хранив например в базе на гитхабе. 

Пример: Область тьмы.

**Comment by ciricc** [comment]
@akseonowww Это трудоемкая задача, расширение было сделано только для визуализации существующих в самом кинопоиске дорожек. Скорее сего эта фича не появится в расширении
