### ISSUE TITLE
1.3.3 manifest problem

### ISSUE THREAD

**Issue by DumDereDum** [ciricc/kinopoisk-dualsubs#6]
Не уверен, что проблема именно в этом, но 1.3.2 у меня поставилась и работает, а 1.3.3 поставилась, но не работает.
P.S. не ставилась из корня, а только из папки `src`
P.S.S. Могу предположить, что не там находится manifest файл
```
Система:

Google 102.0.5005.115 64bit

Win 10

Устанавливал так как написано в ReadMe
```

**Comment by ciricc** [comment]
> Не уверен, что проблема именно в этом, но 1.3.2 у меня поставилась и работает, а 1.3.3 поставилась, но не работает. P.S. не ставилась из корня, а только из папки `src` P.S.S. Могу предположить, что не там находится manifest файл

Привет. Нужно устанавливать не из архива source code, а из скомпилированной версии расширения - [kinopisk-dualsubs-1.3.3.zip](https://github.com/ciricc/kinopoisk-dualsubs/releases/download/1.3.3/kinopoisk-dualsubs-1.3.3.zip)
