### ISSUE TITLE
Все сломалось 😢

### ISSUE THREAD

**Issue by ciricc** [ciricc/kinopoisk-dualsubs#9]
![image](https://user-images.githubusercontent.com/20687373/183533399-40e03845-78de-4b82-99f1-9cdf7ba2497c.png)

**Comment by ilj2x2** [comment]
**Такая же проблема!!!** Очень прошу дать совет. А то уже настолько неприятно смотреть одни русские субтитры, что аккаунт на гитхабе пришлось создать)) Попробовал уже всё, что можно. И в ручную переустанавливал, и через гугл маркет. Помогите, пожалуйста.
